"""
API v1 routes package.
"""

from app.api.v1 import (
    alert_history,
    alert_silences,
    alert_templates,
    alerts,
    assets,
    audit_logs,
    auth,
    dashboard,
    feishu_notifications,
    feishu_sync,
    it_feedback,
    it_feedback_notifications,
    monitor,
    navigation,
    notification_groups,
    notification_records,
    ops,
    pc_client_version,
    permissions,
    roles,
    users,
)

__all__ = [
    "assets",
    "audit_logs",
    "auth",
    "dashboard",
    "feishu_notifications",
    "feishu_sync",
    "it_feedback",
    "it_feedback_notifications",
    "monitor",
    "navigation",
    "notification_groups",
    "notification_records",
    "ops",
    "pc_client_version",
    "permissions",
    "roles",
    "users",
    "alerts",
    "alert_silences",
    "alert_templates",
    "alert_history",
]
