"""Add feishu_open_message_id to alert_history

Revision ID: 045e01fdab36
Revises: 46407530488f
Create Date: 2026-04-02 17:03:20.511197

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '045e01fdab36'
down_revision: str | None = '46407530488f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_alert_receivers_active', table_name='alert_receivers')
    op.drop_table('alert_receivers')
    op.drop_table('notification_group_users')
    op.add_column('alert_history', sa.Column('feishu_open_message_id', sa.String(length=100), nullable=True))
    op.alter_column('alert_history', 'alertname',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.drop_index('idx_alert_history_alertname', table_name='alert_history')
    op.drop_index('idx_alert_history_created', table_name='alert_history')
    op.drop_index('idx_alert_history_status', table_name='alert_history')
    op.create_index(op.f('ix_alert_history_alertname'), 'alert_history', ['alertname'], unique=False)
    op.create_index(op.f('ix_alert_history_id'), 'alert_history', ['id'], unique=False)
    op.create_index(op.f('ix_alert_history_severity'), 'alert_history', ['severity'], unique=False)
    op.alter_column('alert_silences', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('alert_silences', 'match_pattern',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('alert_silences', 'created_by',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Integer(),
               nullable=True,
               postgresql_using='created_by::integer')
    op.drop_index('idx_alert_silences_active', table_name='alert_silences')
    op.drop_index('idx_alert_silences_time', table_name='alert_silences')
    op.create_index(op.f('ix_alert_silences_id'), 'alert_silences', ['id'], unique=False)
    op.create_index(op.f('ix_alert_silences_name'), 'alert_silences', ['name'], unique=False)
    op.create_foreign_key(None, 'alert_silences', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('alert_templates', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('alert_templates', 'template_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('email', 'feishu', name='templatetype', native_enum=False),
               existing_nullable=False)
    op.drop_index('idx_alert_templates_active', table_name='alert_templates')
    op.drop_index('idx_alert_templates_type', table_name='alert_templates')
    op.create_index(op.f('ix_alert_templates_id'), 'alert_templates', ['id'], unique=False)
    op.create_index(op.f('ix_alert_templates_name'), 'alert_templates', ['name'], unique=False)
    op.alter_column('notification_group_members', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('notification_group_members', 'id')
    op.alter_column('notification_groups', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('notification_groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notification_groups', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_notification_groups_name', table_name='notification_groups')
    op.create_index(op.f('ix_notification_groups_id'), 'notification_groups', ['id'], unique=False)
    op.create_index(op.f('ix_terminal_metrics_owner_username'), 'terminal_metrics', ['owner_username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_terminal_metrics_owner_username'), table_name='terminal_metrics')
    op.drop_index(op.f('ix_notification_groups_id'), table_name='notification_groups')
    op.create_index('ix_notification_groups_name', 'notification_groups', ['name'], unique=True)
    op.alter_column('notification_groups', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notification_groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notification_groups', 'description',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('notification_group_members', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('notification_group_members', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_alert_templates_name'), table_name='alert_templates')
    op.drop_index(op.f('ix_alert_templates_id'), table_name='alert_templates')
    op.create_index('idx_alert_templates_type', 'alert_templates', ['template_type'], unique=False)
    op.create_index('idx_alert_templates_active', 'alert_templates', ['is_active'], unique=False)
    op.alter_column('alert_templates', 'template_type',
               existing_type=sa.Enum('email', 'feishu', name='templatetype', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('alert_templates', 'name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_constraint(None, 'alert_silences', type_='foreignkey')
    op.drop_index(op.f('ix_alert_silences_name'), table_name='alert_silences')
    op.drop_index(op.f('ix_alert_silences_id'), table_name='alert_silences')
    op.create_index('idx_alert_silences_time', 'alert_silences', ['starts_at', 'ends_at'], unique=False)
    op.create_index('idx_alert_silences_active', 'alert_silences', ['is_active'], unique=False)
    op.alter_column('alert_silences', 'created_by',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('alert_silences', 'match_pattern',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('alert_silences', 'name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_alert_history_severity'), table_name='alert_history')
    op.drop_index(op.f('ix_alert_history_id'), table_name='alert_history')
    op.drop_index(op.f('ix_alert_history_alertname'), table_name='alert_history')
    op.create_index('idx_alert_history_status', 'alert_history', ['status'], unique=False)
    op.create_index('idx_alert_history_created', 'alert_history', ['created_at'], unique=False)
    op.create_index('idx_alert_history_alertname', 'alert_history', ['alertname'], unique=False)
    op.alter_column('alert_history', 'alertname',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('alert_history', 'feishu_open_message_id')
    op.create_table('notification_group_users',
    sa.Column('notification_group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['notification_group_id'], ['notification_groups.id'], name='notification_group_users_notification_group_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notification_group_users_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_group_id', 'user_id', name='notification_group_users_pkey')
    )
    op.create_table('alert_receivers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('webhook_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('auth_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('auth_secret', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='alert_receivers_pkey')
    )
    op.create_index('idx_alert_receivers_active', 'alert_receivers', ['is_active'], unique=False)
    # ### end Alembic commands ###
