"""add notification_records table

Revision ID: c224b325618a
Revises: 045e01fdab36
Create Date: 2026-04-08 16:25:09.482433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c224b325618a'
down_revision: Union[str, None] = '045e01fdab36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_records',
    sa.Column('user', sa.String(length=100), nullable=False),
    sa.Column('feishu_open_id', sa.String(length=64), nullable=True),
    sa.Column('card_content', sa.Text(), nullable=False),
    sa.Column('message_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='notificationstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('template_name', sa.String(length=100), nullable=True),
    sa.Column('notification_type', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['alert_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_records_feishu_open_id'), 'notification_records', ['feishu_open_id'], unique=False)
    op.create_index(op.f('ix_notification_records_id'), 'notification_records', ['id'], unique=False)
    op.create_index(op.f('ix_notification_records_message_id'), 'notification_records', ['message_id'], unique=False)
    op.create_index(op.f('ix_notification_records_notification_type'), 'notification_records', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notification_records_status'), 'notification_records', ['status'], unique=False)
    op.create_index(op.f('ix_notification_records_template_id'), 'notification_records', ['template_id'], unique=False)
    op.create_index(op.f('ix_notification_records_template_name'), 'notification_records', ['template_name'], unique=False)
    op.create_index(op.f('ix_notification_records_user'), 'notification_records', ['user'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_records_user'), table_name='notification_records')
    op.drop_index(op.f('ix_notification_records_template_name'), table_name='notification_records')
    op.drop_index(op.f('ix_notification_records_template_id'), table_name='notification_records')
    op.drop_index(op.f('ix_notification_records_status'), table_name='notification_records')
    op.drop_index(op.f('ix_notification_records_notification_type'), table_name='notification_records')
    op.drop_index(op.f('ix_notification_records_message_id'), table_name='notification_records')
    op.drop_index(op.f('ix_notification_records_id'), table_name='notification_records')
    op.drop_index(op.f('ix_notification_records_feishu_open_id'), table_name='notification_records')
    op.drop_table('notification_records')
    # ### end Alembic commands ###
