"""Add owner_name to asset

Revision ID: bf7b8f22ad21
Revises: be2745244769
Create Date: 2026-03-19 14:13:47.470984

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bf7b8f22ad21'
down_revision: str | None = 'be2745244769'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('owner_name', sa.String(length=100), nullable=True))
    op.alter_column('assets', 'source',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'manual'::assetsource"))
    op.alter_column('assets', 'sync_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'pending'::syncstatus"))
    op.drop_index('ix_assets_source', table_name='assets')
    op.drop_index('ix_assets_sync_status', table_name='assets')
    op.alter_column('audit_logs', 'before_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'after_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('ix_audit_logs_status', table_name='audit_logs')
    op.drop_index('ix_it_feedbacks_status', table_name='it_feedbacks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_it_feedbacks_status', 'it_feedbacks', ['status'], unique=False)
    op.create_index('ix_audit_logs_status', 'audit_logs', ['status'], unique=False)
    op.alter_column('audit_logs', 'after_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'before_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index('ix_assets_sync_status', 'assets', ['sync_status'], unique=False)
    op.create_index('ix_assets_source', 'assets', ['source'], unique=False)
    op.alter_column('assets', 'sync_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'pending'::syncstatus"))
    op.alter_column('assets', 'source',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'manual'::assetsource"))
    op.drop_column('assets', 'owner_name')
    # ### end Alembic commands ###
